apiVersion: akamai.terasky.com/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: akamai-creds
      namespace: crossplane-system
      key: credentials
